apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ include "prometheus-kubelet-stats-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-kubelet-stats-exporter.chart" . }}
  name: {{ template "prometheus-kubelet-stats-exporter.fullname" . }}
rules:
  - apiGroups:
    - ""
    resources:
    - nodes/metrics
    - nodes/stats
    - nodes/proxy
    - nodes # Required when running as a Deployment, to query API for list of nodes
    verbs:
    - get
    - list # Required when running as Deployment
