apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-kubelet-stats-exporter.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-kubelet-stats-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-kubelet-stats-exporter.chart" . }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
